name: Node.js Publish (GitHub) 

on:
  push:
    branchs: [main,master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node_version }} 🔧
      uses: actions/setup-node@v1
      with:
        node-version: 15
        registry-url: 'https://npm.pkg.github.com'
    - name: Install 🔧
      run: yarn install
    - name: Build lerna 🔧
      run: lerna run build
    - name: Publish 🚀
      run: npm publish
      
