name: Node.js Publish (GitHub) 

on:
  push:
    branchs: [main,master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node_version }} 🔧
      uses: actions/setup-node@v1
      with:
        node-version: 15
        registry-url: 'https://npm.pkg.github.com'
    - name: <NPM> Authenticate with GitHub package registry
      run: |
          # echo "//npm.pkg.github.com:_authToken=${{ secrets.CI_TOKEN }}" >> .npmrc 
          # echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_TOKEN }}" >> .npmrc
          # git update-index --assume-unchanged .npmrc
    - name: Install lerna 🔧
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        npm install --global lerna
    - name: Install typescript 🔧
      run: |
        npm i typescript -g
    - name: Install module 🔧
      run: lerna bootstrap
    - name: Build lerna 🔧
      run: lerna run build
    - name: Publish 🚀
      run: lerna publish --yes
      
