name: Node.js Publish (GitHub) 

on:
  push:
    branchs: [main,master,test-npm]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node_version }} 🔧
      uses: actions/setup-node@v2
      with:
        node-version: 15
        registry-url: 'https://npm.pkg.github.com'
        scope: '@lctech-jasper'
    - name: Install lerna 🔧
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        yarn global add lerna
    - name: Install typescript 🔧
      run: |
        yarn global add typescript
    - name: Install module 🔧
      run: lerna bootstrap
      env:
        NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}
    - name: Build module 🔧
      run: lerna run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}
    - name: Publish module 🔧
      run: lerna publish --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}
      
